# Generated by Django 2.1.5 on 2019-06-26 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0003_auto_20190626_0511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbl_oas_errordetails',
            options={'verbose_name_plural': 'tbl_OAS_ERRORDETAILS'},
        ),
    ]
