# Generated by Django 2.1.5 on 2019-06-26 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0006_delete_repos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbl_oas_errordetails',
            options={},
        ),
    ]
